[[redirects]]
  from = "/lin-tree-solver/*"
  to = "https://eager-wescoff-8fd2b7.netlify.app/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/contact/"
  to = "/"
  status = 301

[[redirects]]
  from = "/blog/setup-gitlab-cicd-on-kubernetes.html"
  to = "/blog/install-gitlab-runner-kubernetes/"
  status = 301

[[redirects]]
  from = "/blog/simple-database.html"
  to = "/blog/simple-database/"
  status = 301

[[redirects]]
  from = "/blog/simple-database/motivation-design.html"
  to = "/blog/simple-database/motivation-design/"
  status = 301

[[redirects]]
  from = "/blog/simple-database/memtable.html"
  to = "/blog/simple-database/memtable/"
  status = 301

[[redirects]]
  from = "/blog/simple-database/wal.html"
  to = "/blog/simple-database/wal/"
  status = 301