[[redirects]]
  from = "/lin-tree-solver/*"
  to = "https://statuesque-taiyaki-c2d264.netlify.app/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/wisckey-database/*"
  to = "https://wisckey-database.netlify.app/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/sat-dashboard/*"
  to = "https://sleepy-kirch-6a23b9.netlify.app/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/contact/"
  to = "/"
  status = 301

[[redirects]]
  from = "/blog/setup-gitlab-cicd-on-kubernetes.html"
  to = "/blog/install-gitlab-runner-kubernetes/"
  status = 301

[[redirects]]
  from = "/blog/simple-database.html"
  to = "/blog/simple-database/"
  status = 301

[[redirects]]
  from = "/blog/simple-database/motivation-design.html"
  to = "/blog/simple-database/motivation-design/"
  status = 301

[[redirects]]
  from = "/blog/simple-database/memtable.html"
  to = "/blog/simple-database/memtable/"
  status = 301

[[redirects]]
  from = "/blog/simple-database/wal.html"
  to = "/blog/simple-database/wal/"
  status = 301